### ISSUE TITLE
Saving vi memory from PPLib

### ISSUE THREAD

**Issue by WinstonHChou** [jsimpso81/PathPlannerLabVIEW#7]
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/317ee4b7-bf5a-49f6-b36c-9194706ab49b)
I'm not really familiar with this part of LabVIEW where it always asks me to save vi that is inside the Library, which I know I shouldn't.
But it becomes really annoying when the message jumps out every time.
I think maybe it's because "separate compiled code from source" isn't check for each vi in the Library?

**Comment by jsimpso81** [comment]
Generally day yes to saving library routines.   Especially if you are certain you didn’t make any changes.   On Jan 25, 2024, at 4:57 AM, Winston ***@***.***> wrote:﻿
image.png (view on web)
I'm not really familiar with this part of LabVIEW where it always asks me to save vi that is inside the Library, which I know I shouldn't.
But it becomes really annoying when the message jumps out every time.
I think maybe it's because "separate compiled code from source" isn't check for each vi in the Library?

**Comment by jsimpso81** [comment]
I'll check the "separate compiled code from source".   If you find a specifc VI or VIs that don't have this checked, let me know which ones.
